### ISSUE TITLE
[I/O Site] New Users who sign up  can't install a quickstart on the external site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#32] opened 2022-02-14 18:48 UTC
### Related 

[Video](https://www.youtube.com/watch?v=e5RiKZrfWXs)

### Issue

In the linked video a user who was attempting to sign up and install a quickstart at the same time has an issue with clicking the install button and has to going into NR1 and install the quickstart. We are concerned there may be an issue with identifying the user has an account, thus allowing them to click the install button on the I/O external site to install the quickstart without having to go into NR1.

related to this ticket https://github.com/newrelic/developer-website/issues/1954  as we'd could measure new user install data from the i/o site.

### Acceptance Criteria

- [x] Attempt to reproduce the issue 
- [x] Determine what may be the problem
- [ ] Identify the work to resolve it we find a problem (issue 1)
- [ ] Identify the work to resolve it we find a problem (issue 2)
- [ ] Document the process for how we use cookies to allow installation of quickstart

Tessen Query

> This seems to show the instance of a bad cookie on install

```
FROM TessenAction SELECT * WHERE fullArtifactId LIKE 'install-newrelic%' and eventName = 'INSTALL_GuidedInstall_badQuickstartsCookie'
```

### Expected

- After signing up, the quickstart context is not lost. The user should be taken to a quickstart summary page to continue installing in the product. After some initial troubleshooting it appears that the quickstart cookie may not be set correctly or is getting lost in the sign up flow.

- Once logged in, the user is taken to a sign up screen. without needing to  refresh the external I/O page after singing up / signing in. .

**Comment by jpvajda** [comment] 2022-02-14 21:25
After discussing this as a team, we de-prioritized the urgency with @polfliet

**Comment by JuliaNocera** [comment] 2022-02-16 02:32
Hopefully some helpful additional info:

**There seem to be two issues here**
1. After signing up, the quickstart context is lost. The user should be taken to a quickstart summary page to continue installing in the product. This is a bug. After some initial troubleshooting it appears that the quickstart cookie may not be set correctly or is getting lost in the sign up flow. 

2. Once logged in, the user is still taken to a sign up screen. This is resolved if you refresh the external I/O page after singing up / signing in. I imagine that’s not desired behavior but gives us a clue as to what’s going wrong. 

**Reproducible steps (and issues) below:**
1. Open a private browser
2. navigtae to netlify quickstart
3. click to install quickstart
4. Go through login flow
5. **BROKEN FLOW** after logging in, I am not taken to the quickstart summary

_[try again]_
1. Go back to Netlify quickstart in external I/O tab
2. Click install quickstart again
3. **BROKEN FLOW** Still taken to sign up page

_[try one more time]_
1. Go back to Netlify quickstart in external I/O tab
2. Refresh tab
3. Click to install quickstart
4. I am taken to the correct place, the quickstart summary page

**Comment by aswanson-nr** [comment] 2022-02-17 00:22
Findings:
The `ajs_user_id` is what we use to decide whether to send a user to `one.newrelic.com` or to `newrelic.com/signup`. Unfortunately, that cookie is set by Tessen to allow for analytics tracking and many ad blockers will prevent this from being set, causing the "sign up loop". 
To be clear, this is **only** an issue for users with ad blockers. 

Possible solutions:
1. We get a cookie setup specifically for this use case.
2. User's are always linked to the platform and if they're new, they will have to click the "create account" link.

Another discussed solution was to have the signup flow handle a referrer url through the process. Unfortunately, this still doesn't achieve what we want because the user will still hit the login page before the signup page.

**Comment by jpvajda** [comment] 2022-02-17 00:47
`option 1:` isn't 100% guaranteed as the cookie could change on the service side, which is owned by AAA but we can ask them to not change it. But it seems like a incremental change that is a good improvement. Ideally we can measure the improvement. 

`option 2:` isn't a good experience, we can eliminate that. 😄 

`option 3:` needs further exploration it sounds like it's option 2, + AAA fixing the referral URL problem

`option 4:` A magical solution where the platform knows where to send the user based on their account state (new vs. existing) and also we know what quickstart install to send the to.

**Comment by aaronbassett** [comment] 2022-02-17 02:56
> To be clear, this is **only** an issue for users with ad blockers.

We shouldn't let that be a reason for us to downplay the issue though.

- Globally, 42.7% of internet users use ad blockers (27% of Americans)
- The Adblock extension alone has >65M users
   -- [Hootsuite](https://www.hootsuite.com/resources/digital-trends)

**Comment by aswanson-nr** [comment] 2022-02-17 23:36
Another update: Spoke with AAA again after the initial cookie idea fell through and they recommended we speak to an architect. I'll be setting up some time with them to go over the problem.

**Comment by jpvajda** [comment] 2022-02-18 00:54
@polfliet Just any FYI on this, as we discussed our initial solution and it sounds like we have to re-approach the use of this cookie.

**Comment by nr-kkenney** [comment] 2022-02-18 18:03
moving this to blocked while we decide on what to do next.

**Comment by jpvajda** [comment] 2022-02-18 23:04
After a long discussion the login and New relic, the team has recommended we send all users to the login screen and not to signup, it's the only change DevEn can make as the rest of the challenges lie in the platform, and with the AAA team. There is  a diagram I can share internally as to what we found and how we got to this decision.

**Comment by aswanson-nr** [comment] 2022-02-18 23:14
Potential resolution PR: https://github.com/newrelic/instant-observability-website/pull/38
Waiting for confirmation next week before this will be merged. It removes the logic to direct users to the sign up and always directs them into the platform.

**Closed** 2022-02-22 19:57 UTC
Labels: bug, eng, P2, sp:3

**Comment by jpvajda** [comment] 2022-02-22 20:01
closed as there is no site fix to implement at this time.  #38 has an explaination of next steps that will take.
