### ISSUE TITLE
[I/O Site] Selecting category in sidebar scrolls page to top

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/instant-observability-website#89] opened 2022-03-12 00:36 UTC
## Summary
When selecting a category filter for quickstarts, the page scrolls to the top of the page without any transition

## Steps to reproduce

1. Navigate to [I/O Site](https://newrelic.com/instant-observability)
2. Scroll down the quickstart results
3. Click a category to filter
4. Page scrolls back to the top

## Acceptance Criteria
- [ ] Disable the scrolling behavior
- [ ] Ensure selecting any category or repeated category does not scroll back to the top of the page

**Comment by hveerendranath** [comment] 2022-03-17 16:51
@jpvajda created ticket CXPUI-37 to take care, you may close this PR. Thought of asking once selecting the category scrolling up to top of the tiles isnt it a expected behavior? because user can see the list of tiles under that category.  If its expected behavior then why do we need to fix it? I created a bug in JIRA because you reported.

**Comment by jpvajda** [comment] 2022-03-17 18:32
@hveerendranath  I'm adding @josephgregoryii as he reported this to see if he as some ideas of how to handle the scroll to the top transition more smoothly. We _could_ leave this as is, but it's a bit jarring to the end user. So if there is a better way to handle it with code, I'll defer to Joe on that for some guidance.

**Comment by jpvajda** [comment] 2022-03-17 18:44
closing as we don't need to worry about this for now.

**Closed by jpvajda** 2022-03-17 18:44 UTC
Labels: bug, estimate needed, P3, CXP-UI

**Comment by josephgregoryii** [comment] 2022-03-17 19:04
Putting the reference we had previously on the developer site for this issue:

https://github.com/newrelic/developer-website/blob/250fe206e2ee2fa71e1b2d050be7ce913bcd03c2/gatsby-browser.js#L58-L75
